<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10914" started-at="2018-12-08T15:19:48Z" finished-at="2018-12-08T15:19:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10914" started-at="2018-12-08T15:19:48Z" finished-at="2018-12-08T15:19:59Z">
      <class name="Dafater_Auto_MyOwn.Selenuim.LoginPage_Test">
        <test-method status="PASS" signature="Initiation(java.lang.String)[pri:0, instance:Dafater_Auto_MyOwn.Selenuim.LoginPage_Test@523884b2]" name="Initiation" is-config="true" duration-ms="11007" started-at="2018-12-08T15:19:37Z" finished-at="2018-12-08T15:19:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initiation -->
        <test-method status="FAIL" signature="Login_With_Valid_Data()[pri:0, instance:Dafater_Auto_MyOwn.Selenuim.LoginPage_Test@523884b2]" name="Login_With_Valid_Data" duration-ms="10440" started-at="2018-12-08T15:19:48Z" finished-at="2018-12-08T15:19:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Dasboard] but found [Dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Dasboard] but found [Dashboard]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Dafater_Auto_MyOwn.Selenuim.LoginPage_Test.Login_With_Valid_Data(LoginPage_Test.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_With_Valid_Data -->
        <test-method status="PASS" signature="ScreenshotOnFailure(org.testng.ITestResult)[pri:0, instance:Dafater_Auto_MyOwn.Selenuim.LoginPage_Test@523884b2]" name="ScreenshotOnFailure" is-config="true" duration-ms="438" started-at="2018-12-08T15:19:58Z" finished-at="2018-12-08T15:19:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login_With_Valid_Data status=FAILURE method=LoginPage_Test.Login_With_Valid_Data()[pri:0, instance:Dafater_Auto_MyOwn.Selenuim.LoginPage_Test@523884b2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ScreenshotOnFailure -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:Dafater_Auto_MyOwn.Selenuim.LoginPage_Test@523884b2]" name="TearDown" is-config="true" duration-ms="886" started-at="2018-12-08T15:19:59Z" finished-at="2018-12-08T15:20:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- Dafater_Auto_MyOwn.Selenuim.LoginPage_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
